name: Github Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ✅ Properly set up Rust 1.88.0 and cargo 1.88.0
      - uses: actions/setup-rust@v1
        with:
          rust-version: 1.88.0

      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Download and install Trunk binary
        run: wget -qO- https://github.com/thedodd/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-

      - name: Build
        run: ./trunk build --release --public-url $public_url
        env:
          public_url: "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          single-commit: true
